baseurl: "https://example.com"
languageCode: "en-us"
title: "Fluxy Flux"
theme: "hugo-tania"

params:
  titleEmoji: '🎨'
  socialOptions:
     
    instagram: "https://www.instagram.com/fluxy_flux_/"

menu:
  header:
    - name: Artwork
      url: "/masterpiece/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
